version: "2"
linters:
  enable:
    - asciicheck
    - bodyclose
    - err113
    #- forcetypeassert # disable for now until code base is in a better place
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
  
  settings:
    govet:
      enable:
      # https://google.github.io/styleguide/go/best-practices#shadowing
        - shadow
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        text: 'shadow: declaration of "err" shadows declaration at'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      # https://google.github.io/styleguide/go/decisions#import-grouping
      local-prefixes:
        - github.com/gnzdotmx
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
