on:
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yaml
    permissions:
      contents: read
      actions: read
      pull-requests: write
    strategy:
      matrix:
        test:
          - os: macos-13
          - os: macos-latest
            report-coverage: true
      fail-fast: false
    name: MacOS test (${{ matrix.test.os }})
    with:
      os: "${{ matrix.test.os }}"
      report-coverage: ${{ matrix.test.report-coverage || false }}
      pull-request-number: "${{ github.event.pull_request.number }}"


  